spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${YG_AI_DB_URL:jdbc:sqlserver://192.168.0.112\SREVER2012;databaseName=hicisdata_yg_backup_2026_03_12;encrypt=true;trustServerCertificate=true;}
#    url: ${YG_AI_DB_URL:jdbc:sqlserver://192.168.0.112\SREVER2012;databaseName=hicisdata_yg_backup_2026_03_12;encrypt=true;trustServerCertificate=true;}
    username: ${YG_AI_DB_USERNAME:sa}
    password: ${YG_AI_DB_PASSWORD:Abcd@1234}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
  data:
    redis:
      host: ${YG_AI_REDIS_HOST:127.0.0.1}
      port: ${YG_AI_REDIS_PORT:6379}
      database: ${YG_AI_REDIS_DB:0}
  ai:
    openai:
      api-key: ${YG_AI_OPENAI_API_KEY:EMPTY}
      base-url: ${YG_AI_OPENAI_BASE_URL:http://192.168.0.205:6001}
      chat:
        options:
          model: ${YG_AI_OPENAI_MODEL:Qwen3.5-27B-FP8}

infection:
  pipeline:
    model-permits: 12
    shared-threads: 16
    normalize-window-start-hours: 0,12
    normalize-window-duration-hours: 4
  monitor:
    enqueue-fixed-delay: ${YG_AI_MONITOR_ENQUEUE_FIXED_DELAY:60000}
    collect-fixed-delay: ${YG_AI_MONITOR_ENQUEUE_FIXED_DELAY:60000}
    max-attempts: ${YG_AI_MONITOR_MAX_ATTEMPTS:3}
    retry-delay-seconds: ${YG_AI_MONITOR_RETRY_DELAY_SECONDS:60}
    recent-admission-days: ${YG_AI_MONITOR_RECENT_ADMISSION_DAYS:180}
    debug-mode: ${YG_AI_MONITOR_DEBUG_MODE:true}
    debug-reqnos: ${YG_AI_MONITOR_DEBUG_REQNOS:260221118,260302506,260304621,260218553,260220893,260304412,260215773,260218494,260217042}
#    debug-reqnos: ${YG_AI_MONITOR_DEBUG_REQNOS:260124371,260118051,260122324,260117982,260219321,260300231,260217201}
  format:
    max-attempts: ${YG_AI_FORMAT_MAX_ATTEMPTS:3}
    retry-delay-seconds: ${YG_AI_FORMAT_RETRY_DELAY_SECONDS:60}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
