package com.zzhy.yg_ai.domain.enums;

public enum InfectionNodeType {
    EVENT_EXTRACTOR,
    STRUCTURED_FACT_REFINEMENT,
    CASE_JUDGE,
    NEW_ONSET_JUDGE,
    AFTER_48H_JUDGE,
    PROCEDURE_ASSOCIATION_JUDGE,
    INFECTION_POLARITY_JUDGE,
    SITE_ATTRIBUTION_JUDGE,
    SEVERITY_JUDGE,
    EXPLANATION_GENERATOR,
    FINAL_AUDIT_PLANNING_ONLY
}
